#!/bin/bash
# make by G.R.H

. /mnt/mod/ctrl/configs/functions &>/dev/null 2>&1
progdir="$(cd $(dirname "$0") || exit; pwd)"

case $1 in
    ebook) # E-book conversion code
        python3 "$progdir"/convert.py
        sync
    ;;
    
    add) # Create random flag
        case $(cat /mnt/vendor/oem/language.ini) in
            0|1)
                FLG_FILE="-游戏盲盒-"
            ;;
            *)
                FLG_FILE="-Random-"
            ;;
        esac
        touch /mnt/mod/ctrl/configs/random.flg
        for TF in /mnt/mmc/Roms /mnt/sdcard/Roms
        do
            if [ -d "$TF" ]; then
                for DIR in  A5200 A7800 A800 AMIGA A2600 ATARIST ATOMISWAVE CPS1 CPS2 CPS3    \
                            C64 DOS DREAMCAST FBNEO FC FDS GB GBA GBC GG HBMAME     \
                            LYNX MAME MD MDCD MSX N64 NAOMI NEOGEO NGP PCE      \
                            PGM2 POKE SEGA32X SFC SMS VARCADE VB VIC20 WS
                do
                    rm -f "$TF/$DIR"/{-游戏盲盒*,-随机游戏*,-Random*}
                    [[ ! $(ls -A $TF/$DIR) = "" ]] && (echo "G.R.H" > "$TF/$DIR/$FLG_FILE".zip)
                done
            
                for DIR in  GW NDS OPENBOR PCECD PICO PS SATURN
                do
                    rm -f "$TF/$DIR"/{-游戏盲盒*,-随机游戏*,-Random*}
                done
            
                [[ ! $(ls -A $TF/GW) == "" ]] && (echo "G.R.H" > "$TF/GW/$FLG_FILE".mgw)
                [[ ! $(ls -A $TF/PCECD) == "" ]] && (echo "G.R.H" > "$TF/PCECD/$FLG_FILE".cue)
                [[ ! $(ls -A $TF/PICO) == "" ]] && (echo "G.R.H" > "$TF/PICO/$FLG_FILE".p8)
                [[ ! $(ls -A $TF/PS) == "" ]] && (echo "G.R.H" > "$TF/PS/$FLG_FILE".chd)
                [[ ! $(ls -A $TF/SATURN) == "" ]] && (echo "G.R.H" > "$TF/SATURN/$FLG_FILE".chd)
            fi
        done
    ;;
    del) # Del random flag
        rm -f /mnt/mod/ctrl/configs/random.flg
        for TF in /mnt/mmc/Roms /mnt/sdcard/Roms
        do
            if [ -d "$TF" ]; then
                for DIR in  A5200 A7800 A800 AMIGA A2600 ATARIST ATOMISWAVE CPS1 CPS2 CPS3    \
                            C64 DOS DREAMCAST FBNEO FC FDS GB GBA GBC GG HBMAME VIC20    \
                            LYNX MAME MD MDCD MSX N64 NAOMI NDS NEOGEO NGP OPENBOR PCE      \
                            PGM2 POKE SEGA32X SFC SMS VARCADE VB WS GW PCECD PICO PS SATURN
                do
                    rm -f "$TF/$DIR"/{-游戏盲盒*,-随机游戏*,-Random*}
                done
            fi
        done
    ;;
    st) # Simple Terminal
        HOME=/root
        "$(dirname "$0")"/SimpleTerminal
    ;;
    
    apps) # Reinstall apps
        touch /mnt/mod/update_me
    ;;

    bezels) # Reinstall bezels
        board_info=$(head -n 1 /mnt/vendor/oem/board.ini)
        case $board_info in
            "RG28xx")
                [ -f "/mnt/mod/update/mod/data/28.dep" ] && unzip -oq /mnt/mod/update/mod/data/28.dep -d /
            ;;
            "RGcubexx")
                [ -f "/mnt/mod/update/mod/data/hdmi.dep" ] && unzip -oq /mnt/mod/update/mod/data/hdmi.dep -d /
                [ -f "/mnt/mod/update/mod/data/cube.dep" ] && unzip -oq /mnt/mod/update/mod/data/cube.dep -d /
            ;;
            "RG34xx")
                [ -f "/mnt/mod/update/mod/data/hdmi.dep" ] && unzip -oq /mnt/mod/update/mod/data/hdmi.dep -d /
                [ -f "/mnt/mod/update/mod/data/34.dep" ] && unzip -oq /mnt/mod/update/mod/data/34.dep -d /
            ;;
            "RG34xxSP"|"RGSP")
                [ -f "/mnt/mod/update/mod/data/hdmi.dep" ] && unzip -oq /mnt/mod/update/mod/data/hdmi.dep -d /
                [ -f "/mnt/mod/update/mod/data/34.dep" ] && unzip -oq /mnt/mod/update/mod/data/34.dep -d /
                [ -f "/mnt/mod/update/mod/data/34sp.dep" ] && unzip -oq /mnt/mod/update/mod/data/34sp.dep -d /
            ;;
            *)
                [ -f "/mnt/mod/update/mod/data/hdmi.dep" ] && unzip -oq /mnt/mod/update/mod/data/hdmi.dep -d /
                [ -f "/mnt/mod/update/mod/data/35.dep" ] && unzip -oq /mnt/mod/update/mod/data/35.dep -d /
            ;;
        esac
    ;;

    ra) # Rescue retroarch
        for MPATH in sdcard mmc
        do
            BACKUP_FILE="/mnt/${MPATH}/anbernic/backup/rescue.bak"
            if [ -f $BACKUP_FILE ]; then
                tar -xmf $BACKUP_FILE -C /
                user_quit
            fi
        done
        if [ -f "$(dirname "$0")"/ra_cfg.zip ]; then
            unzip -oq "$(dirname "$0")"/ra_cfg.zip -d /tmp
            UPDATE_DIR=/tmp/ra_cfg
            if [ -d $UPDATE_DIR ]; then
                ROOT_DIR=/.config/retroarch
                RA_ORI_CFG=/mnt/vendor/deep/retro/retroarch.cfg
                board_info=$(head -n 1 /mnt/vendor/oem/board.ini)
                
                rm -rf $ROOT_DIR/retroarch*.cfg
                rm -f /mnt/vendor/ctrl/setRA.sh
                cp -f "$UPDATE_DIR/retroarch_${board_info}.cfg" $RA_ORI_CFG
                cp -f "$UPDATE_DIR/setRA.sh" /mnt/vendor/ctrl/setRA.sh
                cp -f /mnt/mod/ctrl/configs/default.ttf /mnt/vendor/bin/default.ttf
                chmod 755 /mnt/mod/ctrl/RA_launch.sh
                chmod 755 /mnt/vendor/ctrl/setRA.sh
                
                LANG=$(head -n 1 /mnt/vendor/oem/language.ini)
                RA_lang=(12 11 0 1 10 3 9 4 2 7)
                /mnt/vendor/ctrl/setRA.sh rest
                /mnt/vendor/ctrl/setRA.sh adv
                if [[ $LANG -ge 0 && $LANG -lt ${#RA_lang[@]} ]]; then
                    /mnt/vendor/ctrl/setRA.sh language ${RA_lang[${LANG}]}
                fi
            fi
        fi
    ;;
esac

user_quit
